#file=results/rho_lower.random.txt; echo -e "BreastMammaryTissue\tColonTransverse\tLung\tMuscleSkeletal\tOvary\tProstate\tTestis\tWholeBlood" > $file;
#paste <(awk '{print $1,$3}' results/BreastMammaryTissue.cor.stats.random.cpg.gene.pairs.txt | tr ' ' '\t' | sed "s/\t$/\tNA/g") <(awk '{print $3}' results/ColonTransverse.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $3}' results/Lung.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $3}' results/MuscleSkeletal.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $3}' results/Ovary.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $3}' results/Prostate.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $3}' results/Testis.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $3}' results/WholeBlood.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") | grep -v rho_lower >> $file

file=results/rho.random.txt; echo -e "BreastMammaryTissue\tColonTransverse\tLung\tMuscleSkeletal\tOvary\tProstate\tTestis\tWholeBlood" > $file;
paste <(awk '{print $1,$4}' results/BreastMammaryTissue.cor.stats.random.cpg.gene.pairs.txt | tr ' ' '\t' | sed "s/\t$/\tNA/g") <(awk '{print $4}' results/ColonTransverse.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $4}' results/Lung.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $4}' results/MuscleSkeletal.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $4}' results/Ovary.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $4}' results/Prostate.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $4}' results/Testis.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $4}' results/WholeBlood.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") | grep -v rho >> $file

#file=results/rho_upper.random.txt; echo -e "BreastMammaryTissue\tColonTransverse\tLung\tMuscleSkeletal\tOvary\tProstate\tTestis\tWholeBlood" > $file;
#paste <(awk '{print $1,$5}' results/BreastMammaryTissue.cor.stats.random.cpg.gene.pairs.txt | tr ' ' '\t' | sed "s/\t$/\tNA/g") <(awk '{print $5}' results/ColonTransverse.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $5}' results/Lung.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $5}' results/MuscleSkeletal.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $5}' results/Ovary.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $5}' results/Prostate.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $5}' results/Testis.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $5}' results/WholeBlood.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") | grep -v rho_upper >> $file

#file=results/pvalue.random.txt; echo -e "BreastMammaryTissue\tColonTransverse\tLung\tMuscleSkeletal\tOvary\tProstate\tTestis\tWholeBlood" > $file;
#paste <(awk '{print $1,$6}' results/BreastMammaryTissue.cor.stats.random.cpg.gene.pairs.txt | tr ' ' '\t' | sed "s/\t$/\tNA/g") <(awk '{print $6}' results/ColonTransverse.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $6}' results/Lung.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $6}' results/MuscleSkeletal.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $6}' results/Ovary.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $6}' results/Prostate.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $6}' results/Testis.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $6}' results/WholeBlood.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") | grep -v pvalue >> $file

#file=results/padj.random.txt; echo -e "BreastMammaryTissue\tColonTransverse\tLung\tMuscleSkeletal\tOvary\tProstate\tTestis\tWholeBlood" > $file;
#paste <(awk '{print $1,$7}' results/BreastMammaryTissue.cor.stats.random.cpg.gene.pairs.txt | tr ' ' '\t' | sed "s/\t$/\tNA/g") <(awk '{print $7}' results/ColonTransverse.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $7}' results/Lung.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $7}' results/MuscleSkeletal.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $7}' results/Ovary.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $7}' results/Prostate.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $7}' results/Testis.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $7}' results/WholeBlood.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") | grep -v padj >> $file

file=results/ttest.random.txt; echo -e "BreastMammaryTissue\tColonTransverse\tLung\tMuscleSkeletal\tOvary\tProstate\tTestis\tWholeBlood" > $file;
paste <(awk '{print $1,$8}' results/BreastMammaryTissue.cor.stats.random.cpg.gene.pairs.txt | tr ' ' '\t' | sed "s/\t$/\tNA/g") <(awk '{print $8}' results/ColonTransverse.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $8}' results/Lung.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $8}' results/MuscleSkeletal.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $8}' results/Ovary.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $8}' results/Prostate.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $8}' results/Testis.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $8}' results/WholeBlood.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") | grep -v ttest >> $file

file=results/ttest_se.random.txt; echo -e "BreastMammaryTissue\tColonTransverse\tLung\tMuscleSkeletal\tOvary\tProstate\tTestis\tWholeBlood" > $file;
paste <(awk '{print $1,$9}' results/BreastMammaryTissue.cor.stats.random.cpg.gene.pairs.txt | tr ' ' '\t' | sed "s/\t$/\tNA/g") <(awk '{print $9}' results/ColonTransverse.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $9}' results/Lung.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $9}' results/MuscleSkeletal.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $9}' results/Ovary.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $9}' results/Prostate.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $9}' results/Testis.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") <(awk '{print $9}' results/WholeBlood.cor.stats.random.cpg.gene.pairs.txt | sed "s/^$/NA/g") | grep -v ttest_se >> $file
